# config/column_aliases.yml

code_utilisateur:
  - Identifiant
  - Identifiant Local
  - CODE_UTILISATEUR
  - CUTI
  - UTICOD
  - Code utilisateur
  - Identifiant utilisateur


nom_prenom:
  - NomComplet
  - Nom et Prénoms
  - Nom de Famille
  - Prénom(s)
  - NOM_UTILISATEUR
  - LIB
  - Nom et Prénoms utilisateur
  - Nom et Prénom
  - NOMU
  - UTINOM
  
  

profil:
  - Profil utilisateur
  - Intitulé du poste
  - PROFIL
  - LPUTI
  - LPRO
  - PROFCOD
  - position
  - Intitule de poste
  - profil

direction:
  - LBSER
  - Direction
  - LSER
  - Libelle service
  - LIBELLE SERVICE

last_login:
  - DateDerniereModif
  - DATE_DERNIÈRE_CONNEXION
  - date_de_derniere_connexion
  - DATE DE DERNIERE CONNEXION

status:
  - ACTI
  - ACTIF
  - Statut du compte Suspendu
  - SUS
  - SUSP
  - SUSPENDU
  - SS

extraction_date:
  - DATE_EXTRACTION
